CREATE DATABASE [Plateful]

CREATE TABLE [dbo].[Avaliacao_Estabelecimento](
	[ID_AVALIACAO_ESTABELECIMENTO] [int] IDENTITY(1,1) NOT NULL,
	[AVALIACAO_USUARIO] [varchar](500) NOT NULL,
	[NOTA_USUARIO] [tinyint] NOT NULL,
	[URL_IMAGEM_USUARIO] [varchar](240) NULL,
	[ID_ESTABELECIMENTO] [int] NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
	[DATA_AVALIACAO] [datetime] NOT NULL,
	[ESTADO_NOVO] [varchar](50) NULL,
	[ESTADO_ANTERIOR] [varchar](50) NULL,
 CONSTRAINT [PK_Avaliacao_Estabelecimento_1] PRIMARY KEY CLUSTERED 
(
	[ID_AVALIACAO_ESTABELECIMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Avaliacao_Item](
	[ID_AVALIACAO_ITEM] [int] IDENTITY(1,1) NOT NULL,
	[AVALIACAO_USUARIO] [varchar](500) NOT NULL,
	[NOTA_USUARIO] [tinyint] NOT NULL,
	[DATA_AVALIACAO] [datetime] NOT NULL,
	[ID_ITEM] [int] NOT NULL,
	[ID_ESTABELECIMENTO] [int] NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
 CONSTRAINT [PK_Avaliacao_Item] PRIMARY KEY CLUSTERED 
(
	[ID_AVALIACAO_ITEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categoria](
	[ID] [tinyint] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Categoria] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estabelecimento](
	[ID_ESTABELECIMENTO] [int] IDENTITY(1,1) NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
	[URL_IMAGEM_ESTABELECIMENTO] [varchar](240) NOT NULL,
	[UNIDADE] [varchar](120) NULL,
	[ID_ESTADO] [tinyint] NOT NULL,
	[ID_ITEM] [int] NULL,
	[ENDERECO] [varchar](100) NULL,
	[DESCRICAO] [varchar](300) NULL,
 CONSTRAINT [PK_Estabelecimento] PRIMARY KEY CLUSTERED 
(
	[ID_ESTABELECIMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estado](
	[ID] [tinyint] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Estado] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Item](
	[ID_ITEM] [int] IDENTITY(1,1) NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
	[ID_ESTABELECIMENTO] [int] NOT NULL,
	[TITULO_ITEM] [varchar](120) NOT NULL,
	[URL_IMAGEM_ITEM] [varchar](240) NOT NULL,
	[PRECO] [float] NOT NULL,
	[FLAG_CONSUMIDO] [bit] NOT NULL,
	[ID_CATEGORIA] [tinyint] NOT NULL,
 CONSTRAINT [PK_Item] PRIMARY KEY CLUSTERED 
(
	[ID_ITEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tipo_Usuario](
	[ID] [tinyint] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Tipo_Usuario] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[ID_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[EMAIL] [varchar](50) NOT NULL,
	[SENHA] [varchar](240) NOT NULL,
	[NOME_COMPLETO] [varchar](120) NOT NULL,
	[ID_TIPO_USUARIO] [tinyint] NOT NULL,
	[CNPJ] [varchar](30) NULL,
	[NOME_FANTASIA] [varchar](120) NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Categoria] ON 
GO
INSERT [dbo].[Categoria] ([ID], [DESCRICAO]) VALUES (1, N'Entrada')
GO
INSERT [dbo].[Categoria] ([ID], [DESCRICAO]) VALUES (2, N'Principal')
GO
INSERT [dbo].[Categoria] ([ID], [DESCRICAO]) VALUES (3, N'Sobremesa')
GO
INSERT [dbo].[Categoria] ([ID], [DESCRICAO]) VALUES (4, N'Bebida')
GO
SET IDENTITY_INSERT [dbo].[Categoria] OFF
GO
SET IDENTITY_INSERT [dbo].[Estado] ON 
GO
INSERT [dbo].[Estado] ([ID], [DESCRICAO]) VALUES (1, N'Anúncio')
GO
INSERT [dbo].[Estado] ([ID], [DESCRICAO]) VALUES (2, N'Quero ir')
GO
INSERT [dbo].[Estado] ([ID], [DESCRICAO]) VALUES (3, N'Já fui')
GO
INSERT [dbo].[Estado] ([ID], [DESCRICAO]) VALUES (4, N'N/A')
GO
SET IDENTITY_INSERT [dbo].[Estado] OFF
GO
SET IDENTITY_INSERT [dbo].[Tipo_Usuario] ON 
GO
INSERT [dbo].[Tipo_Usuario] ([ID], [DESCRICAO]) VALUES (1, N'Cliente')
GO
INSERT [dbo].[Tipo_Usuario] ([ID], [DESCRICAO]) VALUES (2, N'Estabelecimento')
GO
SET IDENTITY_INSERT [dbo].[Tipo_Usuario] OFF
GO
ALTER TABLE [dbo].[Avaliacao_Estabelecimento]  WITH CHECK ADD  CONSTRAINT [FK_Avaliacao_Estabelecimento_Estabelecimento] FOREIGN KEY([ID_ESTABELECIMENTO])
REFERENCES [dbo].[Estabelecimento] ([ID_ESTABELECIMENTO])
GO
ALTER TABLE [dbo].[Avaliacao_Estabelecimento] CHECK CONSTRAINT [FK_Avaliacao_Estabelecimento_Estabelecimento]
GO
ALTER TABLE [dbo].[Avaliacao_Item]  WITH CHECK ADD  CONSTRAINT [FK_Avaliacao_Item_Item] FOREIGN KEY([ID_ITEM])
REFERENCES [dbo].[Item] ([ID_ITEM])
GO
ALTER TABLE [dbo].[Avaliacao_Item] CHECK CONSTRAINT [FK_Avaliacao_Item_Item]
GO
ALTER TABLE [dbo].[Estabelecimento]  WITH CHECK ADD  CONSTRAINT [FK_Estabelecimento_Estado] FOREIGN KEY([ID_ESTADO])
REFERENCES [dbo].[Estado] ([ID])
GO
ALTER TABLE [dbo].[Estabelecimento] CHECK CONSTRAINT [FK_Estabelecimento_Estado]
GO
ALTER TABLE [dbo].[Estabelecimento]  WITH CHECK ADD  CONSTRAINT [FK_Estabelecimento_Item] FOREIGN KEY([ID_ITEM])
REFERENCES [dbo].[Item] ([ID_ITEM])
GO
ALTER TABLE [dbo].[Estabelecimento] CHECK CONSTRAINT [FK_Estabelecimento_Item]
GO
ALTER TABLE [dbo].[Estabelecimento]  WITH CHECK ADD  CONSTRAINT [FK_Estabelecimento_Usuario] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[Usuario] ([ID_USUARIO])
GO
ALTER TABLE [dbo].[Estabelecimento] CHECK CONSTRAINT [FK_Estabelecimento_Usuario]
GO
ALTER TABLE [dbo].[Item]  WITH CHECK ADD  CONSTRAINT [FK_Item_Categoria] FOREIGN KEY([ID_CATEGORIA])
REFERENCES [dbo].[Categoria] ([ID])
GO
ALTER TABLE [dbo].[Item] CHECK CONSTRAINT [FK_Item_Categoria]
GO
ALTER TABLE [dbo].[Usuario]  WITH CHECK ADD  CONSTRAINT [FK_Usuario_Tipo_Usuario] FOREIGN KEY([ID_TIPO_USUARIO])
REFERENCES [dbo].[Tipo_Usuario] ([ID])
GO
ALTER TABLE [dbo].[Usuario] CHECK CONSTRAINT [FK_Usuario_Tipo_Usuario]
GO
USE [master]
GO
ALTER DATABASE [Plateful] SET  READ_WRITE 
GO
